# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-19 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170419_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('Python技术', 'Python技术'), ('数据库技术', '数据库技术'), ('经济学', '经济学'), ('文本咨询', '文本咨询'), ('个人心情', '个人心情'), ('其他', '其他')], default=('其他', '其他'), max_length=20),
        ),
        migrations.AlterField(
            model_name='moment',
            name='user_name',
            field=models.CharField(default='匿名', max_length=20),
        ),
    ]
